add the Skill model
TechLadies/ppis pull request #1
Opened 2016-09-26 04:12 UTC by cherye

This PR adds the Skill model to contain the list of skills that a volunteer can choose from.

2016-09-26 13:12 UTC, anthonysherwinchua commented on app/models/skill.rb
> +	validates :name, presence: true, uniqueness: { case_sensitive: false }
please change the setting of your editor to use 2 spaces instead of tab or 4 spaces.

2016-09-26 13:13 UTC, anthonysherwinchua commented on db/seeds.rb
> +"Academic",
change this to a mutli line, maximizing the 120 character per line

2016-09-26 13:13 UTC, anthonysherwinchua commented on test/fixtures/skills.yml
> +# Read about fixtures at http://api.rubyonrails.org/classes/ActiveRecord/FixtureSet.html
remove this file, as we are not going to use unit test

2016-09-26 13:13 UTC, anthonysherwinchua commented on test/models/skill_test.rb
> +require 'test_helper'
remove this file, as we are not going to use unit test

2016-09-26 13:14 UTC, anthonysherwinchua requested changes

2016-09-29 13:47 UTC, anthonysherwinchua requested changes
looks a bit better, but there are still some things that need polishing

2016-09-29 13:47 UTC, anthonysherwinchua commented on Gemfile
> +gem 'slim'
can move this below the `coffee-rails` gem?

2016-09-29 13:47 UTC, anthonysherwinchua commented on app/controllers/centers_controller.rb
> +class CentersController < ApplicationController
please fix the indentions on this file

2016-09-29 13:47 UTC, anthonysherwinchua commented on app/controllers/centers_controller.rb
> +		@center = Center.find(params[:center_id])
the `create` action is meant to create an object. Here you are just looking for and redirecting to its details page

2016-09-29 13:47 UTC, anthonysherwinchua commented on app/views/centers/show.html.slim
> +  body
as explained last night, the layout is already set on the `/app/views/layouts` and should not be repeated on each of your view

2016-09-29 13:47 UTC, anthonysherwinchua commented on app/views/centers/show.html.slim
> +    form_for([@center, @center.centers.build]) do |f| %>
missing `=` before `form_for` and an extra `%>` at the end

2016-09-29 13:47 UTC, anthonysherwinchua commented on app/views/centers/show.html.slim
> +      p This example shows you how a basic Slim file looks.
need to remove this

2016-09-29 13:47 UTC, anthonysherwinchua commented on app/views/centers/show.html.slim
> +        - for center in centers
prefer to use the syntax `- centers.each do |center|`

2016-09-29 13:47 UTC, anthonysherwinchua commented on db/migrate/20160926032922_create_skills.rb
> +class CreateSkills < ActiveRecord::Migration[5.0]
I think this is misplaced. This branch is for Center

2016-09-29 13:47 UTC, anthonysherwinchua commented on db/schema.rb
> +  end
schema contains skills, but not the center. Think you have mixed it up

2016-09-29 13:47 UTC, anthonysherwinchua commented on db/seeds.rb
> +
remove extra line

2016-09-29 13:47 UTC, anthonysherwinchua commented on db/seeds.rb
> +	Skill.create(name: name)
outdent this line 1x

2016-09-29 13:48 UTC, anthonysherwinchua commented
oh, I think i'm the one mistaken. This branch is for Skill, not Center. So move all the Center stuffs to its branch

2016-09-30 00:11 UTC, anthonysherwinchua requested changes

2016-09-30 00:11 UTC, anthonysherwinchua commented on db/seeds.rb
> +	Skill.create(name: name)
outdent this please

2016-10-03 17:12 UTC, cherye commented on app/views/centers/show.html.slim
> +    form_for([@center, @center.centers.build]) do |f| %>
i have deleted this file.

2016-10-03 17:13 UTC, cherye commented on db/seeds.rb
> +
do you mean to remove all extra lines or just one specific extra line?

2016-10-03 17:14 UTC, cherye commented on app/views/centers/show.html.slim
> +      p This example shows you how a basic Slim file looks.
this has been deleted last week.

2016-10-03 17:14 UTC, cherye commented on app/controllers/centers_controller.rb
> +class CentersController < ApplicationController
this has been fixed last week.

2016-10-03 17:14 UTC, cherye commented on app/models/skill.rb
> +	validates :name, presence: true, uniqueness: { case_sensitive: false }
this has been done last week.

2016-10-03 17:15 UTC, cherye commented on db/seeds.rb
> +"Academic",
this has been done last week.

2016-10-03 17:15 UTC, cherye commented on test/fixtures/skills.yml
> +# Read about fixtures at http://api.rubyonrails.org/classes/ActiveRecord/FixtureSet.html
this file has been removed last week.

2016-10-03 17:15 UTC, cherye commented on test/models/skill_test.rb
> +require 'test_helper'
this file has been removed last week.

2016-10-03 17:15 UTC, cherye commented on Gemfile
> +gem 'slim'
this has been relocated last week.

2016-10-03 17:16 UTC, cherye commented on app/views/centers/show.html.slim
> +  body
this has been removed last week

2016-10-03 17:17 UTC, cherye commented on app/views/centers/show.html.slim
> +        - for center in centers
this file has been deleted last week.

2016-10-03 17:18 UTC, cherye commented on db/seeds.rb
> +	Skill.create(name: name)
outdent which line? lines 8-14? or a specific line?

2016-10-03 17:20 UTC, cherye commented on db/seeds.rb
> +	Skill.create(name: name)
outdent lines 8-12? or do you mean unindent lines 8-12?

2016-10-04 03:48 UTC, cherye commented on app/models/skill.rb
> +	validates :name, presence: true, uniqueness: { case_sensitive: false }
checked and change is updated on github.

2016-10-04 03:48 UTC, cherye commented on db/seeds.rb
> +"Academic",
checked and change is reflected on github.

2016-10-04 03:48 UTC, cherye commented on app/models/skill.rb
> +	validates :name, presence: true, uniqueness: { case_sensitive: false }
checked and change is reflected on github.

2016-10-04 03:52 UTC, cherye commented on Gemfile
> +gem 'slim'
checked and change is reflected on github.

2016-10-04 03:55 UTC, cherye commented on app/controllers/centers_controller.rb
> +class CentersController < ApplicationController
file has been removed because it was in the wrong branch

2016-10-04 03:55 UTC, cherye commented on app/controllers/centers_controller.rb
> +		@center = Center.find(params[:center_id])
file has been removed because it was in the wrong branch

2016-10-04 03:56 UTC, cherye commented on app/views/centers/show.html.slim
> +  body
file has been removed because no longer using slim at the moment

2016-10-04 03:56 UTC, cherye commented on app/views/centers/show.html.slim
> +  body
file has been removed because it was in the wrong branch

2016-10-04 03:57 UTC, cherye commented on app/views/centers/show.html.slim
> +      p This example shows you how a basic Slim file looks.
file has been removed because it was in the wrong branch

2016-10-04 03:57 UTC, cherye commented on app/views/centers/show.html.slim
> +    form_for([@center, @center.centers.build]) do |f| %>
file has been removed because it was in the wrong branch

2016-10-04 03:57 UTC, cherye commented on app/views/centers/show.html.slim
> +        - for center in centers
file has been removed because it was in the wrong branch.

2016-10-04 03:58 UTC, cherye commented on app/views/centers/show.html.slim
> +        - for center in centers
file has been removed because it was in the wrong branch

2016-10-04 04:03 UTC, cherye commented on db/seeds.rb
> +	Skill.create(name: name)
checked and change is reflected on github.

2016-10-04 17:59 UTC, merged