add the FormalEducation model and its seed
TechLadies/ppis pull request #2
Opened 2016-09-26 05:22 UTC by cherye

This PR adds the FormalEducation model which contains the list of formal educational levels that a volunteer can choose from.

2016-09-26 13:14 UTC, anthonysherwinchua commented on app/models/formal_education.rb
> +	validates :name, presence: true, uniqueness: { case_sensitive: false }
same as the other comment about changing the default behaviour of your editor -- 2 spaces instead of tab or 4 spaces

2016-09-26 13:15 UTC, anthonysherwinchua commented on db/seeds.rb
> +formal_educations = ["N Level", "O Level", "A Level", "NITEC", "Higher NITEC", "Diploma", "Degree", "Master", "PhD", "Other"]
bring down the "Other", as this is already over the 120 character limit per line

2016-09-26 13:16 UTC, anthonysherwinchua commented on test/fixtures/formal_educations.yml
> +# Read about fixtures at http://api.rubyonrails.org/classes/ActiveRecord/FixtureSet.html
remove this file please -- we're not going to use unit test

2016-09-26 13:16 UTC, anthonysherwinchua commented on test/models/formal_education_test.rb
> +require 'test_helper'
remove this file please -- we're not going to use unit test

2016-09-26 13:17 UTC, anthonysherwinchua commented on db/schema.rb
> +  create_table "certifications", force: :cascade do |t|
remove this block. I think this is a result of other migration from another branch

2016-09-26 13:17 UTC, anthonysherwinchua commented on db/schema.rb
> +  create_table "skills", force: :cascade do |t|
remove this block. I think this is a result of other migration from another branch

2016-09-26 13:18 UTC, anthonysherwinchua requested changes

2016-10-04 04:07 UTC, cherye commented on app/models/formal_education.rb
> +	validates :name, presence: true, uniqueness: { case_sensitive: false }
checked and change is reflected on github.

2016-10-04 04:11 UTC, cherye commented on db/seeds.rb
> +formal_educations = ["N Level", "O Level", "A Level", "NITEC", "Higher NITEC", "Diploma", "Degree", "Master", "PhD", "Other"]
checked and change is reflected on github.

2016-10-04 04:11 UTC, cherye commented on test/fixtures/formal_educations.yml
> +# Read about fixtures at http://api.rubyonrails.org/classes/ActiveRecord/FixtureSet.html
file has been removed.

2016-10-04 04:12 UTC, cherye commented on test/models/formal_education_test.rb
> +require 'test_helper'
file has been removed.

2016-10-04 04:13 UTC, cherye commented on db/schema.rb
> +  create_table "certifications", force: :cascade do |t|
checked and change is reflected on github.

2016-10-04 04:13 UTC, cherye commented on db/schema.rb
> +  create_table "skills", force: :cascade do |t|
checked and change is reflected on github.

2016-10-04 17:53 UTC, merged