add admin model with devise
TechLadies/ppis pull request #24
Opened 2016-10-14 13:57 UTC by cherye

this PR adds the admin model with devise and allows admin to sign in at url "/admins/sign_in".

2016-10-14 16:37 UTC, anthonysherwinchua requested changes

2016-10-14 16:37 UTC, anthonysherwinchua commented on spec/models/admin_spec.rb
> +require 'rails_helper'
can remove this?

2016-10-14 16:37 UTC, anthonysherwinchua commented on spec/factories/admins.rb
> +FactoryGirl.define do
can remove this?

2016-10-14 16:37 UTC, anthonysherwinchua commented on app/models/concerns/Accessible
> +module Accessible
can you give a reference where you followed this?

2016-10-15 15:07 UTC, anthonysherwinchua requested changes

2016-10-15 15:07 UTC, anthonysherwinchua commented on app/assets/javascripts/admin.js.coffee
> -#= require_self
please put this back.. this will be used next time we need a page-specific javascript

2016-10-15 15:07 UTC, anthonysherwinchua commented on app/controllers/application_controller.rb
> +  # before_action :authenticate_volunteer!
remove commented out code please

2016-10-15 15:07 UTC, anthonysherwinchua commented on app/models/concerns/Accessible
> +module Accessible
remove this file. We don't need it 😄

2016-10-15 15:07 UTC, anthonysherwinchua commented on config/application.rb
> +  ActionMailer::Base.smtp_settings = {
remove this please, we have already set up the mailer for development on config/environments/development.rb

2016-10-15 15:07 UTC, anthonysherwinchua commented on db/schema.rb
> +  create_table "highest_educations", force: :cascade do |t|
remove this please. rollback on highest education branch

2016-10-16 08:14 UTC, cherye commented on app/assets/javascripts/admin.js.coffee
> -#= require_self
it's really strange, i cannot find this file. i can only find admin.coffee (don't have admin.js.coffee)

2016-10-16 08:15 UTC, cherye commented on app/assets/javascripts/admin.js.coffee
> -#= require_self
and the line #= require_self is inside admin.coffee file.

2016-10-17 14:38 UTC, anthonysherwinchua approved these changes
some minor changes and 🚀

2016-10-17 14:38 UTC, anthonysherwinchua commented on app/views/layouts/admin.html.slim
> +    = stylesheet_link_tag 'admin', media: 'all', 'data-turbolinks-track' => true
remove the change here. We removed `turbolinks` on this project

2016-10-17 14:38 UTC, anthonysherwinchua commented on db/seeds.rb
> +
remove extra line please

2016-10-17 14:38 UTC, anthonysherwinchua commented on config/application.rb
> +
remove extra line pleaes

2016-10-17 16:08 UTC, merged